name: Update DNS Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'dnsconfig.js'
      - 'Domains/**'
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: DNSControl preview
        uses: wblondel/dnscontrol-action@v4
        id: dnscontrol_preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_API_ACCOUNTID: ${{ vars.CLOUDFLARE_API_ACCOUNTID }}
        with:
          args: --no-colors=false preview
  push:
    runs-on: ubuntu-latest
    needs: preview
    steps:
      - uses: actions/checkout@v5
      - name: DNSControl push
        uses: wblondel/dnscontrol-action@v4
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_API_ACCOUNTID: ${{ vars.CLOUDFLARE_API_ACCOUNTID }}
        with:
          args: --no-colors=false push
